repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/oca/pylint-odoo
    rev: v9.1.5
    hooks:
      - id: pylint-odoo
        entry: pylint
        args:
          - "--load-plugins=pylint_odoo"
          - "--rcfile=.pylintrc"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.53.0
    hooks:
      - id: eslint
        files: \.(js|xml)$
        additional_dependencies:
          - eslint@8.53.0
          - eslint-plugin-owl@0.0.1
